Sistema-de-inventario-master/apps/inventario/urls.py
from django.contrib import admin
from django.urls import path 
from django.conf.urls import url , include
from . import views
from apps.inventario.views import UsuarioCreate, UsuarioList,usuarioDelete,EquipamientoCreate, AsignacionCreate, pdaCreate, telefonoCreate, UsuarioUpdate,usuarioShow,equipoList,equipoUpdate,equipoDelete,equipoShow,asignacionList,asignacionUpdate,asignacionDelete,asignacionShow,pdaList,pdaUpdate,pdaDelete,pdaShow,telegonoList,telefonoUpdate,telefonoDelete,telefonoShow,ReporteEquipoExcel,ReporteAsignacionExcel,ReportePdaExcel,ReporteTelefonoExcel,equipoBuscar,asignacionBuscar,pdaBuscar,telefonoBuscar

app_name = 'inventario'

urlpatterns = [
    #URL paginas principales y login

    
    url(r'^$', views.singIn),
    url(r'^postsign/', views.postsign),
    url(r'^logout/',views.logout,name='log'),
    url(r'^informe/',views.informe,name='informe'),
   
    #URLS para mostrar usuarios
    url(r'^nuevoUsuario/', UsuarioCreate.as_view(), name='usuario_crear'),
    url(r'^listarUsuario/', UsuarioList.as_view(), name='usuario_listar'),
    url(r'^EliminarUsuario/(?P<pk>\d+)/$', usuarioDelete.as_view(), name='usuario_eliminar'),
    url(r'^EditarUsuario/(?P<pk>\d+)/$', UsuarioUpdate.as_view(), name='usuario_editar'),
    url(r'^mostrarUsuario/(?P<pk>\d+)/$', usuarioShow.as_view(), name='usuario_mostrar'),
    # URLS para equipamiento
    url(r'^nuevoEquipo/', EquipamientoCreate.as_view(),name='equipo_crear'),
    url(r'^listarequipo/',equipoList.as_view(),name='equipo_listar'),
    url(r'^editarEquipo/(?P<pk>\d+)/$',equipoUpdate.as_view(),name='equipo_editar'),
    url(r'^eliminarEquipo/(?P<pk>\d+)/$',equipoDelete.as_view(),name='equipo_eliminar'),
    url(r'^mostrarEquipo/(?P<pk>\d+)/$',equipoShow.as_view(),name='equipo_mostrar'),
    url(r'^reporte_excel_equipo/',ReporteEquipoExcel.as_view(),name='equipo_reporte'),
    url(r'^buscarEquipo/', views.equipoBuscar, name='equipo_buscar'),
  
    #URLS para asignacion
    url(r'^nuevaAsignacion/', AsignacionCreate.as_view(),name='asignacion_crear'),
    url(r'^listarAsignacion/',asignacionList.as_view(),name='asignacion_listar'),
    url(r'^editarAsignacion/(?P<pk>\d+)/$',asignacionUpdate.as_view(),name='asignacion_editar'),
    url(r'^eliminarAsignacion/(?P<pk>\d+)/$',asignacionDelete.as_view(),name='asignacion_eliminar'),
    url(r'^mostrarAsignacion/(?P<pk>\d+)/$',asignacionShow.as_view(),name='asignacion_mostrar'),
    url(r'^reporte_excel_asignacion/',ReporteAsignacionExcel.as_view(),name='asignacion_reporte'),
    url(r'^buscarAsignacion/', views.asignacionBuscar,name='asignacion_buscar'),
    #URLS para pda
    url(r'^nuevaPda/', pdaCreate.as_view(),name='pda_crear'),
    url(r'^listarpda/',pdaList.as_view(),name='pda_listar'),
    url(r'^editarPda/(?P<pk>\d+)/$',pdaUpdate.as_view(),name='pda_editar'),
    url(r'^eliminarPda/(?P<pk>\d+)/$',pdaDelete.as_view(),name='pda_eliminar'),
    url(r'^mostrarPda/(?P<pk>\d+)/$',pdaShow.as_view(),name='pda_mostrar'),
    url(r'^reporte_excel_pda/',ReportePdaExcel.as_view(),name='pda_reporte'),
    url(r'^buscarPDA/',views.pdaBuscar,name='pda_buscar'),
    #URL para telefono
    url(r'^nuevoTelefono/', telefonoCreate.as_view(),name='telefono_crear'),
    url(r'^listarTelefono/',telegonoList.as_view(),name='telefono_listar'),
    url(r'^editarTelefono/(?P<pk>\d+)/$',telefonoUpdate.as_view(),name='telefono_editar'),
    url(r'^eliminarTelefono/(?P<pk>\d+)/$',telefonoDelete.as_view(),name='telefono_eliminar'),
    url(r'^mostrarTelefono/(?P<pk>\d+)/$',telefonoShow.as_view(),name='telefono_mostrar'),
    url(r'^reporte_excel_telefono/',ReporteTelefonoExcel.as_view(),name='telefono_reporte'),
    url(r'^buscarTelefono/',views.telefonoBuscar, name='telefono_buscar'),
]

Sistema-de-inventario-master/mantenedor/urls.py
from django.contrib import admin
from django.urls import path 
from django.conf.urls import url , include







urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'',include('apps.inventario.urls')),
   
    #urls de inventario
    url(r'^usuario/', include('apps.inventario.urls', namespace='usuario')),
    url(r'^equipo/',include('apps.inventario.urls', namespace='equipos')),
    url(r'^asignacion/',include('apps.inventario.urls', namespace='Asignacion')),
    url(r'^pda/',include('apps.inventario.urls', namespace='pda')),
    url(r'^telefono/',include('apps.inventario.urls', namespace='telefono')),
    
]

Sistema-de-inventario-master/templates/usuario/Usuario_form.html
{% extends "base/base.html" %}

<div class="container mt-5 my-5">

{% block contenido %}
    
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success" type="submit">Registrar</button>
        <a class="btn btn-primary" href="#">Cancelar</a>
    </form>

{% endblock %}
</div>

Sistema-de-inventario-master/templates/usuario/usuario_delete.html
{% extends "base/base.html" %}

<div class="container mt-5 my-5">

{% block contenido %}
    
    <form method="POST">
        {% csrf_token %}
        <h3>Desea eliminar el registro de {{object.nombre}}?</h3>
        <button class="btn btn-danger" type="submit">Si,eliminar</button>
        <a class="btn btn-default" href="{% url 'usuario:usuario_listar' %}">Cancelar</a>
        
    </form>

{% endblock %}
</div>

Sistema-de-inventario-master/templates/usuario/usuario_list.html
{% extends "base/base.html" %}

<div class="container mt-5 my-5">
    {% block contenido %}
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <td>Nombre</td>
                    <td>Apellido</td>
                    <td>Cargo</td>
                    <td>Correo</td>
                </tr>
            </thead>
            <tbody>
                {% if object_list %}
                {% for usuario in object_list %}
                <tr>
                    <td>{{ usuario.nombre}}</td>
                    <td>{{ usuario.apellido}}</td>
                    <td>{{ usuario.cargo}}</td>
                    <td>{{ usuario.email}}</td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'usuario:usuario_mostrar' usuario.id %}">Ver</a>
                        <a class="btn btn-primary" href="{% url 'usuario:usuario_editar' usuario.id %}">Editar</a>
                        <a class="btn btn-danger" href="{% url 'usuario:usuario_eliminar'  usuario.id %}">Eliminar</a>
                    </td>
                </tr>
                {% endfor%}
                {% else %}
                    <h1>no hay registro de usuarios</h1>
                {% endif%}
            </tbody>

        </table>
        <nav aria-label="Page navigation example">
                <ul class="pagination">
                  <li class="page-item">
                    {% if page_obj.has_previous %}
                      <a class="page-link" href="?page={{page_obj.previous_page_number}}">Anterior</a>
                      {% endif%}
                    </li>
                  
                  <li class="page-item">
                        {% if page_obj.has_next %}
                      <a class="page-link" href="?page={{page_obj.next_page_number}}">Siguiente</a>
                      {% endif%}
                </li>
                </ul>
        </nav>
    {% endblock %}
</div>

Sistema-de-inventario-master/templates/usuario/usuario_show.html
{% extends "base/base.html" %}

<div class="container mt-5 my-5">

{% block contenido %}
    <p><strong>Nombre:</strong>{{object.nombre}}</p>
    <p><strong>Apellido:</strong>{{object.apellido}}</p>
    <p><strong>Cargo:</strong>{{object.cargo}}</p>
    <p><strong>Email:</strong>{{object.email}}</p>
    <p><strong>Contraseña:</strong>{{object.contrasena}}</p>

    <a class="btn btn-success" href="{% url 'usuario:usuario_listar' %}">OK</a>
    <a class="btn btn-success" href="{% url 'usuario:usuario_editar' usuario.id %}">Editar</a>
    <a class="btn btn-success" href="{% url 'usuario:usuario_eliminar' usuario.id %}">Eliminar</a>

{% endblock %}
</div>