Sistema-de-inventario-master/apps/inventario/urls.py
from django.contrib import admin
from django.urls import path 
from django.conf.urls import url , include
from . import views
from apps.inventario.views import UsuarioCreate, UsuarioList,usuarioDelete,EquipamientoCreate, AsignacionCreate, pdaCreate, telefonoCreate, UsuarioUpdate,usuarioShow,equipoList,equipoUpdate,equipoDelete,equipoShow,asignacionList,asignacionUpdate,asignacionDelete,asignacionShow,pdaList,pdaUpdate,pdaDelete,pdaShow,telegonoList,telefonoUpdate,telefonoDelete,telefonoShow,ReporteEquipoExcel,ReporteAsignacionExcel,ReportePdaExcel,ReporteTelefonoExcel,equipoBuscar,asignacionBuscar,pdaBuscar,telefonoBuscar

app_name = 'inventario'

urlpatterns = [
    #URL paginas principales y login

    
    url(r'^$', views.singIn),
    url(r'^postsign/', views.postsign),
    url(r'^logout/',views.logout,name='log'),
    url(r'^informe/',views.informe,name='informe'),
   
    #URLS para mostrar usuarios
    url(r'^nuevoUsuario/', UsuarioCreate.as_view(), name='usuario_crear'),
    url(r'^listarUsuario/', UsuarioList.as_view(), name='usuario_listar'),
    url(r'^EliminarUsuario/(?P<pk>\d+)/$', usuarioDelete.as_view(), name='usuario_eliminar'),
    url(r'^EditarUsuario/(?P<pk>\d+)/$', UsuarioUpdate.as_view(), name='usuario_editar'),
    url(r'^mostrarUsuario/(?P<pk>\d+)/$', usuarioShow.as_view(), name='usuario_mostrar'),
    # URLS para equipamiento
    url(r'^nuevoEquipo/', EquipamientoCreate.as_view(),name='equipo_crear'),
    url(r'^listarequipo/',equipoList.as_view(),name='equipo_listar'),
    url(r'^editarEquipo/(?P<pk>\d+)/$',equipoUpdate.as_view(),name='equipo_editar'),
    url(r'^eliminarEquipo/(?P<pk>\d+)/$',equipoDelete.as_view(),name='equipo_eliminar'),
    url(r'^mostrarEquipo/(?P<pk>\d+)/$',equipoShow.as_view(),name='equipo_mostrar'),
    url(r'^reporte_excel_equipo/',ReporteEquipoExcel.as_view(),name='equipo_reporte'),
    url(r'^buscarEquipo/', views.equipoBuscar, name='equipo_buscar'),
  
    #URLS para asignacion
    url(r'^nuevaAsignacion/', AsignacionCreate.as_view(),name='asignacion_crear'),
    url(r'^listarAsignacion/',asignacionList.as_view(),name='asignacion_listar'),
    url(r'^editarAsignacion/(?P<pk>\d+)/$',asignacionUpdate.as_view(),name='asignacion_editar'),
    url(r'^eliminarAsignacion/(?P<pk>\d+)/$',asignacionDelete.as_view(),name='asignacion_eliminar'),
    url(r'^mostrarAsignacion/(?P<pk>\d+)/$',asignacionShow.as_view(),name='asignacion_mostrar'),
    url(r'^reporte_excel_asignacion/',ReporteAsignacionExcel.as_view(),name='asignacion_reporte'),
    url(r'^buscarAsignacion/', views.asignacionBuscar,name='asignacion_buscar'),
    #URLS para pda
    url(r'^nuevaPda/', pdaCreate.as_view(),name='pda_crear'),
    url(r'^listarpda/',pdaList.as_view(),name='pda_listar'),
    url(r'^editarPda/(?P<pk>\d+)/$',pdaUpdate.as_view(),name='pda_editar'),
    url(r'^eliminarPda/(?P<pk>\d+)/$',pdaDelete.as_view(),name='pda_eliminar'),
    url(r'^mostrarPda/(?P<pk>\d+)/$',pdaShow.as_view(),name='pda_mostrar'),
    url(r'^reporte_excel_pda/',ReportePdaExcel.as_view(),name='pda_reporte'),
    url(r'^buscarPDA/',views.pdaBuscar,name='pda_buscar'),
    #URL para telefono
    url(r'^nuevoTelefono/', telefonoCreate.as_view(),name='telefono_crear'),
    url(r'^listarTelefono/',telegonoList.as_view(),name='telefono_listar'),
    url(r'^editarTelefono/(?P<pk>\d+)/$',telefonoUpdate.as_view(),name='telefono_editar'),
    url(r'^eliminarTelefono/(?P<pk>\d+)/$',telefonoDelete.as_view(),name='telefono_eliminar'),
    url(r'^mostrarTelefono/(?P<pk>\d+)/$',telefonoShow.as_view(),name='telefono_mostrar'),
    url(r'^reporte_excel_telefono/',ReporteTelefonoExcel.as_view(),name='telefono_reporte'),
    url(r'^buscarTelefono/',views.telefonoBuscar, name='telefono_buscar'),
]

Sistema-de-inventario-master/mantenedor/urls.py
from django.contrib import admin
from django.urls import path 
from django.conf.urls import url , include







urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'',include('apps.inventario.urls')),
   
    #urls de inventario
    url(r'^usuario/', include('apps.inventario.urls', namespace='usuario')),
    url(r'^equipo/',include('apps.inventario.urls', namespace='equipos')),
    url(r'^asignacion/',include('apps.inventario.urls', namespace='Asignacion')),
    url(r'^pda/',include('apps.inventario.urls', namespace='pda')),
    url(r'^telefono/',include('apps.inventario.urls', namespace='telefono')),
    
]

Sistema-de-inventario-master/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <title>{% block titulo %}{% endblock %}</title>
</head>
<body>
  <div class="container-fluid bg-dark">
      {% block barra %}
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Sistema de inventario</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mr-4">
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    PC y Portatiles
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'equipos:equipo_crear' %}">Agregar Equipamiento</a>
                    <a class="dropdown-item" href="{% url 'equipos:equipo_listar' %}">Modificar Equipamiento</a>
                    <a class="dropdown-item" href="{% url 'equipos:equipo_buscar' %}">Buscar Equipamiento</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Asignación de equipos
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'Asignacion:asignacion_crear' %}">Nueva asignación</a>
                    <a class="dropdown-item" href="{% url 'Asignacion:asignacion_listar' %}">Modificar asignación</a>
                    <a class="dropdown-item" href="{% url 'Asignacion:asignacion_buscar' %}">Buscar asignación</a>
                  </div>
                </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Telefonia
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'telefono:telefono_crear' %}">Agregar Telefonos</a>
                  <a class="dropdown-item" href="{% url 'telefono:telefono_listar' %}">Modificar telefonos</a>
                  <a class="dropdown-item" href="{% url 'telefono:telefono_buscar' %}">Buscar telefonos</a>
                  
                </div>
              </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                PDA
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'pda:pda_crear' %}">Agregar PDA</a>
                <a class="dropdown-item" href="{% url 'pda:pda_listar' %}">Modificar PDA</a>
                <a class="dropdown-item" href="{% url 'pda:pda_buscar' %}">Buscar PDA</a>
              </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'inventario:informe' %}">Informes</a>
              </li> 
            <li class="nav-item">
              <a class="nav-link" href="{% url 'inventario:log' %}">Cerrar Sesión</a>
            </li>           
        </div>
      </nav>
      {% endblock %}
  </div>
  <div class="container mt-5 my-5">
    {% block header %}
    {% endblock %}
</div>
  <div class="container mt-5 my-5">
    {% block contenido %}
    {% endblock %}
  </div>
  

</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

Sistema-de-inventario-master/templates/base/baseLogin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link  rel="stylesheet" href="{% static 'css/login.css' %}">
  <title>{% block titulo %}{% endblock %}</title>
</head>
<body>
  <div class="container-fluid bg-dark">
      {% block barra %}
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Sistema de inventario</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mr-4">
            <li class="nav-item">
              <a class="nav-link" href="#">Contacto</a>
            </li>  
                    
        </div>
        
      </nav>
      {% endblock %}
  </div>
  <div class="container mt-5 my-5">
    {% block header %}
    {% endblock %}
</div>
  <div class="container mt-5 my-5">
    {% block contenido %}
    {% endblock %}
  </div>
  

</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>