Sistema-de-inventario-master/apps/inventario/urls.py
from django.contrib import admin
from django.urls import path 
from django.conf.urls import url , include
from . import views
from apps.inventario.views import UsuarioCreate, UsuarioList,usuarioDelete,EquipamientoCreate, AsignacionCreate, pdaCreate, telefonoCreate, UsuarioUpdate,usuarioShow,equipoList,equipoUpdate,equipoDelete,equipoShow,asignacionList,asignacionUpdate,asignacionDelete,asignacionShow,pdaList,pdaUpdate,pdaDelete,pdaShow,telegonoList,telefonoUpdate,telefonoDelete,telefonoShow,ReporteEquipoExcel,ReporteAsignacionExcel,ReportePdaExcel,ReporteTelefonoExcel,equipoBuscar,asignacionBuscar,pdaBuscar,telefonoBuscar

app_name = 'inventario'

urlpatterns = [
    #URL paginas principales y login

    
    url(r'^$', views.singIn),
    url(r'^postsign/', views.postsign),
    url(r'^logout/',views.logout,name='log'),
    url(r'^informe/',views.informe,name='informe'),
   
    #URLS para mostrar usuarios
    url(r'^nuevoUsuario/', UsuarioCreate.as_view(), name='usuario_crear'),
    url(r'^listarUsuario/', UsuarioList.as_view(), name='usuario_listar'),
    url(r'^EliminarUsuario/(?P<pk>\d+)/$', usuarioDelete.as_view(), name='usuario_eliminar'),
    url(r'^EditarUsuario/(?P<pk>\d+)/$', UsuarioUpdate.as_view(), name='usuario_editar'),
    url(r'^mostrarUsuario/(?P<pk>\d+)/$', usuarioShow.as_view(), name='usuario_mostrar'),
    # URLS para equipamiento
    url(r'^nuevoEquipo/', EquipamientoCreate.as_view(),name='equipo_crear'),
    url(r'^listarequipo/',equipoList.as_view(),name='equipo_listar'),
    url(r'^editarEquipo/(?P<pk>\d+)/$',equipoUpdate.as_view(),name='equipo_editar'),
    url(r'^eliminarEquipo/(?P<pk>\d+)/$',equipoDelete.as_view(),name='equipo_eliminar'),
    url(r'^mostrarEquipo/(?P<pk>\d+)/$',equipoShow.as_view(),name='equipo_mostrar'),
    url(r'^reporte_excel_equipo/',ReporteEquipoExcel.as_view(),name='equipo_reporte'),
    url(r'^buscarEquipo/', views.equipoBuscar, name='equipo_buscar'),
  
    #URLS para asignacion
    url(r'^nuevaAsignacion/', AsignacionCreate.as_view(),name='asignacion_crear'),
    url(r'^listarAsignacion/',asignacionList.as_view(),name='asignacion_listar'),
    url(r'^editarAsignacion/(?P<pk>\d+)/$',asignacionUpdate.as_view(),name='asignacion_editar'),
    url(r'^eliminarAsignacion/(?P<pk>\d+)/$',asignacionDelete.as_view(),name='asignacion_eliminar'),
    url(r'^mostrarAsignacion/(?P<pk>\d+)/$',asignacionShow.as_view(),name='asignacion_mostrar'),
    url(r'^reporte_excel_asignacion/',ReporteAsignacionExcel.as_view(),name='asignacion_reporte'),
    url(r'^buscarAsignacion/', views.asignacionBuscar,name='asignacion_buscar'),
    #URLS para pda
    url(r'^nuevaPda/', pdaCreate.as_view(),name='pda_crear'),
    url(r'^listarpda/',pdaList.as_view(),name='pda_listar'),
    url(r'^editarPda/(?P<pk>\d+)/$',pdaUpdate.as_view(),name='pda_editar'),
    url(r'^eliminarPda/(?P<pk>\d+)/$',pdaDelete.as_view(),name='pda_eliminar'),
    url(r'^mostrarPda/(?P<pk>\d+)/$',pdaShow.as_view(),name='pda_mostrar'),
    url(r'^reporte_excel_pda/',ReportePdaExcel.as_view(),name='pda_reporte'),
    url(r'^buscarPDA/',views.pdaBuscar,name='pda_buscar'),
    #URL para telefono
    url(r'^nuevoTelefono/', telefonoCreate.as_view(),name='telefono_crear'),
    url(r'^listarTelefono/',telegonoList.as_view(),name='telefono_listar'),
    url(r'^editarTelefono/(?P<pk>\d+)/$',telefonoUpdate.as_view(),name='telefono_editar'),
    url(r'^eliminarTelefono/(?P<pk>\d+)/$',telefonoDelete.as_view(),name='telefono_eliminar'),
    url(r'^mostrarTelefono/(?P<pk>\d+)/$',telefonoShow.as_view(),name='telefono_mostrar'),
    url(r'^reporte_excel_telefono/',ReporteTelefonoExcel.as_view(),name='telefono_reporte'),
    url(r'^buscarTelefono/',views.telefonoBuscar, name='telefono_buscar'),
]

Sistema-de-inventario-master/mantenedor/urls.py
from django.contrib import admin
from django.urls import path 
from django.conf.urls import url , include







urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'',include('apps.inventario.urls')),
   
    #urls de inventario
    url(r'^usuario/', include('apps.inventario.urls', namespace='usuario')),
    url(r'^equipo/',include('apps.inventario.urls', namespace='equipos')),
    url(r'^asignacion/',include('apps.inventario.urls', namespace='Asignacion')),
    url(r'^pda/',include('apps.inventario.urls', namespace='pda')),
    url(r'^telefono/',include('apps.inventario.urls', namespace='telefono')),
    
]

Sistema-de-inventario-master/templates/informe/informe.html
{% extends "base/base.html" %}

<div class="container">
{% block contenido%}
<div class="row row-cols-1 row-cols-md-2 g-4 text-center">
    <div class="col">
        <div class="card text-white bg-dark mb-3">
            <div class="card-body">
                <h5 class="card-title">Informe de Equipos</h5>
                <p class="card-text"><iframe style="background: #21313C;border: none;border-radius: 2px;box-shadow: 0 2px 10px 0 rgba(70, 76, 79, .2);" width="440" height="200" src="https://charts.mongodb.com/charts-project-0-pictq/embed/charts?id=19da92bc-09a8-46b0-8469-c55cc80351da&autoRefresh=10&theme=dark"></iframe></p>
                <a href="{% url 'equipos:equipo_reporte' %}" class="btn text-white btn-outline-success">Descargar informe</a>
            </div>
        </div>
    </div>
    <div class="col">
            <div class="card text-white bg-dark mb-3">
                <div class="card-body">
                    <h5 class="card-title">Informe de Asignaciones</h5>
                    <p class="card-text"><iframe style="background: #21313C;border: none;border-radius: 2px;box-shadow: 0 2px 10px 0 rgba(70, 76, 79, .2);" width="440" height="200" src="https://charts.mongodb.com/charts-project-0-pictq/embed/charts?id=8f1d6c50-5792-4ff8-8c20-db378e17d5a5&autoRefresh=10&theme=dark"></iframe></p>
                    <a href="{% url 'Asignacion:asignacion_reporte' %}" class="btn text-white btn-outline-success">Descargar informe</a>
                </div>
            </div>
        </div>
        <div class="col">
                <div class="card text-white bg-dark mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Informe de telefonía</h5>
                        <p class="card-text"><iframe style="background: #21313C;border: none;border-radius: 2px;box-shadow: 0 2px 10px 0 rgba(70, 76, 79, .2);" width="440" height="200" src="https://charts.mongodb.com/charts-project-0-pictq/embed/charts?id=3ae945f0-47bf-4799-8c7e-583085c27232&autoRefresh=10&theme=dark"></iframe></p>
                        <a href="{% url 'telefono:telefono_reporte' %}" class="btn text-white btn-outline-success">Descargar informe</a>
                    </div>
                </div>
            </div>
        <div class="col">
            <div class="card text-white bg-dark mb-3">
                <div class="card-body">
                     <h5 class="card-title">Informe de PDA</h5>
                     <p class="card-text"><iframe style="background: #21313C;border: none;border-radius: 2px;box-shadow: 0 2px 10px 0 rgba(70, 76, 79, .2);" width="440" height="200" src="https://charts.mongodb.com/charts-project-0-pictq/embed/charts?id=d2931c20-ebf1-4e74-89bb-5329e77ce0af&autoRefresh=10&theme=dark"></iframe></p>
                    <a href="{% url 'pda:pda_reporte' %}" class="btn text-white btn-outline-success">Descargar informe</a>
                </div>
            </div>
        </div>
</div>

{% endblock %}
</div>